import { Post, User, Conversation } from '../types';

export const DEMO_USERS: User[] = [
  {
    id: 'user-alex',
    name: 'Alex Rivera',
    username: 'alex_rivera',
    email: 'alex@example.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    bio: '🚀 Full-stack engineer & creator. Building real-time communication systems and rich interfaces on Firebase, Render & Neon!',
    website: 'https://alexrivera.dev',
    location: 'San Francisco, CA',
    isVerified: true,
    followersCount: 1420,
    followingCount: 380,
    postsCount: 24,
    isFollowing: true,
    isFollower: true,
    isMutual: true,
    canChat: true,
    createdAt: '2025-01-15T00:00:00.000Z',
  },
  {
    id: 'user-sarah',
    name: 'Sarah Chen',
    username: 'sarah_chen',
    email: 'sarah@example.com',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1200&auto=format&fit=crop&q=80',
    bio: '✨ Senior Product Designer & Photographer. Visual storytelling, micro-interactions & sleek dark interfaces.',
    website: 'https://sarahchen.design',
    location: 'Tokyo, Japan',
    isVerified: true,
    followersCount: 3290,
    followingCount: 412,
    postsCount: 48,
    isFollowing: true,
    isFollower: true,
    isMutual: true,
    canChat: true,
    createdAt: '2025-02-01T00:00:00.000Z',
  },
  {
    id: 'user-david',
    name: 'David Miller',
    username: 'david_miller',
    email: 'david@example.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    bio: '🎬 Filmmaker, drone pilot & digital nomad. Sharing cinematic clips and behind-the-scenes stories.',
    website: 'https://davidmiller.film',
    location: 'Vancouver, Canada',
    isVerified: false,
    followersCount: 890,
    followingCount: 154,
    postsCount: 19,
    isFollowing: false,
    isFollower: true,
    isMutual: false,
    canChat: true,
    createdAt: '2025-03-10T00:00:00.000Z',
  },
  {
    id: 'user-elena',
    name: 'Elena Rostova',
    username: 'elena_art',
    email: 'elena@example.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=1200&auto=format&fit=crop&q=80',
    bio: '🎨 3D Artist, motion designer & shader enthusiast. Exploring generative art and neon aesthetics.',
    website: 'https://elena-art.studio',
    location: 'Berlin, Germany',
    isVerified: true,
    followersCount: 5120,
    followingCount: 290,
    postsCount: 62,
    isFollowing: false,
    isFollower: false,
    isMutual: false,
    canChat: false, // demonstrates follower-gated locked chat!
    createdAt: '2025-04-05T00:00:00.000Z',
  },
];

export const DEMO_POSTS: Post[] = [
  {
    id: 'demo-post-1',
    content: 'Just deployed the new real-time architecture with WebSockets, Neon PostgreSQL, and Render! The sub-50ms latency is incredible. What do you all think of the dark glassmorphic design? 🚀🔥 #FullStack #WebDev #Engineering',
    media: [
      {
        url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&auto=format&fit=crop&q=80',
        type: 'image',
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    author: {
      id: 'user-alex',
      name: 'Alex Rivera',
      username: 'alex_rivera',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    likesCount: 142,
    commentsCount: 18,
    isLiked: false,
    recentComments: [
      {
        id: 'c1',
        content: 'Looks super clean Alex! Love the color palette and responsiveness 👌',
        createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        user: {
          id: 'user-sarah',
          name: 'Sarah Chen',
          username: 'sarah_chen',
          avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
          isVerified: true,
        },
      },
    ],
  },
  {
    id: 'demo-post-2',
    content: 'Morning light in Tokyo ☀️ Captured these architectural frames during my sunrise walk in Shibuya. Minimalism is about removing everything that distracts from the core essence.',
    media: [
      {
        url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&auto=format&fit=crop&q=80',
        type: 'image',
      },
      {
        url: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&auto=format&fit=crop&q=80',
        type: 'image',
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    author: {
      id: 'user-sarah',
      name: 'Sarah Chen',
      username: 'sarah_chen',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    likesCount: 298,
    commentsCount: 34,
    isLiked: true,
    recentComments: [],
  },
  {
    id: 'demo-post-3',
    content: 'Quick drone flight over the misty mountain ridge earlier today. The dynamic range on this sensor is unreal! Check out the clip below: 🚁🏔️',
    media: [
      {
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        type: 'video',
        thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&auto=format&fit=crop&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    author: {
      id: 'user-david',
      name: 'David Miller',
      username: 'david_miller',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
      isVerified: false,
    },
    likesCount: 87,
    commentsCount: 12,
    isLiked: false,
    recentComments: [],
  },
  {
    id: 'demo-post-4',
    content: 'New 3D loop experiment rendered in Blender Cycles. Playing with volumetric lighting and iridescent materials. ✨🔮',
    media: [
      {
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        type: 'video',
        thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    author: {
      id: 'user-elena',
      name: 'Elena Rostova',
      username: 'elena_art',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    likesCount: 420,
    commentsCount: 56,
    isLiked: false,
    recentComments: [],
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-sarah',
    updatedAt: new Date().toISOString(),
    otherUser: {
      id: 'user-sarah',
      name: 'Sarah Chen',
      username: 'sarah_chen',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    lastMessage: {
      id: 'm1',
      text: 'That looks stunning! The contrast and glow are on point 🔥',
      mediaUrl: null,
      mediaType: null,
      createdAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
      senderId: 'user-alex',
      isRead: true,
    },
    unreadCount: 0,
    chatPermission: {
      canChat: true,
      isFollowing: true,
      isFollower: true,
      isMutual: true,
    },
  },
  {
    id: 'conv-david',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    otherUser: {
      id: 'user-david',
      name: 'David Miller',
      username: 'david_miller',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
      isVerified: false,
    },
    lastMessage: {
      id: 'm2',
      text: 'Hey! Loved your latest post on real-time sockets.',
      mediaUrl: null,
      mediaType: null,
      createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      senderId: 'user-david',
      isRead: false,
    },
    unreadCount: 1,
    chatPermission: {
      canChat: true,
      isFollowing: false,
      isFollower: true,
      isMutual: false,
    },
  },
  {
    id: 'conv-elena',
    updatedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    otherUser: {
      id: 'user-elena',
      name: 'Elena Rostova',
      username: 'elena_art',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    lastMessage: null,
    unreadCount: 0,
    chatPermission: {
      canChat: false,
      reason: 'Follow this user to unlock direct messaging.',
      isFollowing: false,
      isFollower: false,
      isMutual: false,
    },
  },
];
